basePath: /api
definitions:
  auth.authenticateResponse:
    properties:
      jwt:
        type: string
    type: object
  auth.oauthPayload:
    properties:
      code:
        type: string
    type: object
  portainer.Tag:
    properties:
      EndpointGroups:
        additionalProperties:
          type: boolean
        type: object
      Endpoints:
        additionalProperties:
          type: boolean
        type: object
      Name:
        type: string
      id:
        type: integer
    type: object
info:
  contact: {}
  license: {}
  title: PortainerCE
  version: "2.0"
paths:
  /auth/oauth/validate:
    post:
      consumes:
      - application/json
      operationId: authenticate_oauth
      parameters:
      - description: OAuth code
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/auth.oauthPayload'
      produces:
      - application/json
      responses:
        "200":
          description: Token
          schema:
            $ref: '#/definitions/auth.authenticateResponse'
      summary: Authenticate with OAuth
      tags:
      - auth
  /endpoints/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: endpoint id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: ""
        "500":
          description: ""
      summary: Deletes an endpoint
      tags:
      - Endpoints
  /tags:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/portainer.Tag'
            type: array
        "500":
          description: ""
      summary: Fetches the list of tags
      tags:
      - Tags
  /upload/tls/{certificate}:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: certificate type
        enum:
        - ca
        - cert
        - key
        in: path
        name: certificate
        required: true
        type: string
      - description: folder name
        in: query
        name: folder
        required: true
        type: string
      - description: file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "400":
          description: ""
        "500":
          description: ""
      summary: Upload TLS file
      tags:
      - Upload
swagger: "2.0"
